on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Verify git repository
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14


      - name: Install dependencies
        run: npm install

      - name: Execute lint to verify errors
        run: npx eslint .
